# Build Workflow
name: build

# Run on Push
on: [push]

jobs:
  build:
    # Run this on a default linux machine
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: mustafaquraish/aecor
          path: aecor

      - name: Build aecor
        run: |
          cd aecor
          ./meta/bootstrap.sh

      - name: Create build directory
        run: mkdir -p build

      - name: Compile Aecor to C
        run: |
          ./aecor/bootstrap/aecor -l ./aecor/ wasm_main.ae -n

      - name: Build WASM binary
        run: docker run --rm -v $(pwd):/mnt -w /mnt/ emscripten/emsdk ./build_wasm.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build